version: '3.8'

services:
  contact-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=G60_TechChallenge_02;User ID=sa;Password=senha@123;MultipleActiveResultSets=true;TrustServerCertificate=true"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - monitoring
    volumes:
      - ./UserSecrets:/root/.microsoft/usersecrets:ro
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=senha@123
    ports:
      - "1433:1433"
    networks:
      - monitoring
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

networks:
  monitoring:
    driver: bridge

volumes:
  sql_data:
