name: Tech Challenge - Phase Two - Grupo 60

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-build: 

    runs-on: windows-latest

    env:
      Solution_Name: ./src/TechChallenge-PhaseTwo.sln                     # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: ./src/Contact.Test/Contacts.Test.csproj         # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Configuration: Debug
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet build $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet build $env:Test_Project_Path

    - name: Bye-bye
      run: echo Build finalizado!
    
